version: '3.8'
services:
  frontend:
    build: ./frontend/frontend-scaffold
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/frontend-scaffold:/app
    command: npm run dev

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/go/src/app
    command: /server

  llm-service:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    environment:
      - gpus=all
    command: ollama run mistral
