version: '3.8'
services:
  frontend:
    build: ./frontend/frontend-scaffold
    container_name: frontend-scaffold
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    container_name: backend-scaffold
    ports:
      - "8000:8000"
    environment:
      OLLAMA_API_URL: http://ollama:11434

  llm-service:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"

volumes:
  ollama:
